export const SITE_CONFIG = {
  domain: "hongsamkim.com",
  siteUrl: "https://hongsamkim.com",
  brandName: "Hồng Sâm Kim",
  subBrandName: "Hồng Sâm Kim",
  companyName: "Công ty TNHH Thương Mại NA Korea",
  taxId: "0109946846",
  slogan: "Nơi tận tâm trở thành kiệt tác",
  hotline: "0903409939",
  hotlineDisplay: "090.340.9939",
  email: "contact@nakorea.vn",
  address: "LK 19-TT1, khu nhà ở 96-96B Nguyễn Huy Tưởng, Phường Thanh Xuân Trung, Quận Thanh Xuân, Hà Nội",
  streetAddress: "LK 19-TT1, khu nhà ở 96-96B Nguyễn Huy Tưởng",
  addressLocality: "Thanh Xuân",
  addressRegion: "Hà Nội",
  postalCode: "100000",
  addressCountry: "VN",
  geo: {
    latitude: 20.9984,
    longitude: 105.8032,
  },
  openingHours: "Mo-Su 08:00-22:00",
  social: {
    facebook: "https://www.facebook.com/KimRedGinseng",
    instagram: "https://www.instagram.com/kimsredginseng.vietnam/",
    tiktok: "https://www.tiktok.com/@kimsredginsenghq",
    zalo: "https://zalo.me/g/kogger629",
  },
  sameAs: [
    "https://www.facebook.com/KimRedGinseng",
    "https://www.instagram.com/kimsredginseng.vietnam/",
    "https://www.tiktok.com/@kimsredginsenghq",
    "https://zalo.me/g/kogger629",
  ],
  bankInfo: {
    bankName: "MB Bank (Ngân hàng Quân Đội)",
    bankId: "MB",
    accountNumber: "1888888856789",
    accountHolder: "DOÃN TUẤN ANH",
    accountHolderAscii: "DOAN TUAN ANH",
  },
};

